// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chitfund-group/Details.tsx": () => import("../components/mockups/chitfund-group/Details.tsx"),
  "./components/mockups/chitfund-admin/Dashboard.tsx": () => import("../components/mockups/chitfund-admin/Dashboard.tsx"),
  "./components/mockups/chitfund-user/Dashboard.tsx": () => import("../components/mockups/chitfund-user/Dashboard.tsx")
};
